"""Ensure campaigns.status column exists

Revision ID: 9ee68fdb27b8
Revises: 001
Create Date: 2025-09-11 11:16:24.056230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ee68fdb27b8'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recipient_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('click_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unsubscribe_count', sa.Integer(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('unsubscribe_count')
        batch_op.drop_column('click_count')
        batch_op.drop_column('open_count')
        batch_op.drop_column('recipient_count')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
